// ---------------------------------------------------------------------------
// Prebuilt demo definitions for the Composer
// ---------------------------------------------------------------------------

export interface Demo {
  name: string;
  description: string;
  commands: string[];
}

export const DEMOS: Record<string, Demo> = {
  '1': {
    name: 'Hero Landing',
    description: 'Gradient hero with big headline, badge, subtext, and dual CTA buttons',
    commands: [
      // Full-screen gradient background
      'layout stack as hero align=center justify=center style w-full tw:"min-h-screen bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-500 px-4 @md:px-8 py-10 @md:py-20" pad-xl gap-lg',
      // Small badge/chip at top
      'add container as badge style tw:"inline-flex items-center rounded-full bg-white/20 backdrop-blur-sm px-4 py-1.5 text-sm font-medium text-white ring-1 ring-white/30"',
      'place badge in hero/content',
      'add text "Now in Public Beta" as badgeText style tw:"text-white text-sm font-medium"',
      'place badgeText in badge/content',
      // Main headline
      'add text "Build Reactive UIs with Zero Ceremony" as headline style tw:"text-3xl @md:text-5xl font-extrabold text-white tracking-tight text-center leading-tight max-w-3xl"',
      'place headline in hero/content',
      // Subtext
      'add text "No virtual DOM. No hooks. No dependency arrays. Just write code and watch your UI come alive with fine-grained reactivity that updates only what changes." as subtext style tw:"text-lg @md:text-xl text-indigo-100 text-center max-w-2xl leading-relaxed"',
      'place subtext in hero/content',
      // CTA button row
      'layout stack as buttons axis=x wrap=true style gap-md tw:"mt-4 justify-center"',
      'place buttons in hero/content',
      'add button "Get Started Free" as ctaPrimary style tw:"bg-white text-indigo-700 hover:bg-indigo-50 px-6 @md:px-8 py-3 @md:py-3.5 rounded-xl text-base @md:text-lg font-bold shadow-xl shadow-indigo-900/30 transition-all"',
      'place ctaPrimary in buttons/content',
      'add button "View on GitHub" as ctaSecondary style tw:"bg-transparent text-white border-2 border-white/40 hover:border-white hover:bg-white/10 px-6 @md:px-8 py-3 @md:py-3.5 rounded-xl text-base @md:text-lg font-semibold transition-all"',
      'place ctaSecondary in buttons/content',
      // Bottom social proof
      'add text "Trusted by 2,400+ developers worldwide" as proof style tw:"text-indigo-200 text-sm mt-8 tracking-wide"',
      'place proof in hero/content',
    ],
  },
  '2': {
    name: 'Pricing Cards',
    description: 'Three pricing tiers with a highlighted popular card featuring a gradient border',
    commands: [
      // Page wrapper
      'layout stack as page align=center style tw:"min-h-screen bg-slate-950 py-10 @md:py-20 px-4 @md:px-8" gap-lg',
      // Header
      'add text "Simple, Transparent Pricing" as heading style tw:"text-2xl @md:text-4xl font-extrabold text-white tracking-tight text-center"',
      'place heading in page/content',
      'add text "Start free. Scale when you are ready. No surprise fees." as sub style tw:"text-base @md:text-lg text-slate-400 text-center max-w-lg"',
      'place sub in page/content',
      // Cards grid
      'layout grid as cards cols=1 style gap-lg tw:"mt-8 max-w-5xl w-full @md:grid-cols-3"',
      'place cards in page/content',
      // --- Starter card ---
      'layout stack as basic style tw:"bg-slate-900 border border-slate-800 rounded-2xl p-6 @md:p-8 flex flex-col" gap-md',
      'place basic in cards/content',
      'add text "Starter" as basicTitle style tw:"text-lg font-semibold text-slate-300"',
      'place basicTitle in basic/content',
      'add text "$0" as basicPrice style tw:"text-3xl @md:text-5xl font-extrabold text-white"',
      'place basicPrice in basic/content',
      'add text "/month" as basicPer style tw:"text-slate-500 text-sm -mt-3"',
      'place basicPer in basic/content',
      'add divider as basicDiv style tw:"border-slate-800"',
      'place basicDiv in basic/content',
      'add text "Up to 3 projects" as bf1 style tw:"text-slate-400 text-sm"',
      'place bf1 in basic/content',
      'add text "Basic analytics" as bf2 style tw:"text-slate-400 text-sm"',
      'place bf2 in basic/content',
      'add text "Community support" as bf3 style tw:"text-slate-400 text-sm"',
      'place bf3 in basic/content',
      'add button "Get Started" as basicBtn style tw:"mt-auto bg-slate-800 text-white hover:bg-slate-700 px-6 py-3 rounded-xl font-semibold transition-all w-full"',
      'place basicBtn in basic/content',
      // --- Pro card (highlighted) ---
      'layout stack as pro style tw:"bg-gradient-to-b from-indigo-600 to-violet-700 border-2 border-indigo-400 rounded-2xl p-6 @md:p-8 flex flex-col shadow-2xl shadow-indigo-500/25 relative @md:scale-105" gap-md',
      'place pro in cards/content',
      'add container as popularBadge style tw:"absolute -top-4 left-1/2 -translate-x-1/2 bg-gradient-to-r from-amber-400 to-orange-500 text-slate-900 text-xs font-bold uppercase tracking-wider px-4 py-1 rounded-full shadow-lg"',
      'place popularBadge in pro/content',
      'add text "Most Popular" as popularText style tw:"text-xs font-bold text-slate-900 uppercase tracking-wider"',
      'place popularText in popularBadge/content',
      'add text "Pro" as proTitle style tw:"text-lg font-semibold text-indigo-100 mt-2"',
      'place proTitle in pro/content',
      'add text "$29" as proPrice style tw:"text-3xl @md:text-5xl font-extrabold text-white"',
      'place proPrice in pro/content',
      'add text "/month" as proPer style tw:"text-indigo-200 text-sm -mt-3"',
      'place proPer in pro/content',
      'add divider as proDiv style tw:"border-indigo-400/40"',
      'place proDiv in pro/content',
      'add text "Unlimited projects" as pf1 style tw:"text-indigo-100 text-sm"',
      'place pf1 in pro/content',
      'add text "Advanced analytics & reports" as pf2 style tw:"text-indigo-100 text-sm"',
      'place pf2 in pro/content',
      'add text "Priority email support" as pf3 style tw:"text-indigo-100 text-sm"',
      'place pf3 in pro/content',
      'add text "Custom integrations" as pf4 style tw:"text-indigo-100 text-sm"',
      'place pf4 in pro/content',
      'add button "Start Free Trial" as proBtn style tw:"mt-auto bg-white text-indigo-700 hover:bg-indigo-50 px-6 py-3 rounded-xl font-bold transition-all w-full shadow-lg"',
      'place proBtn in pro/content',
      // --- Enterprise card ---
      'layout stack as enterprise style tw:"bg-slate-900 border border-slate-800 rounded-2xl p-6 @md:p-8 flex flex-col" gap-md',
      'place enterprise in cards/content',
      'add text "Enterprise" as entTitle style tw:"text-lg font-semibold text-slate-300"',
      'place entTitle in enterprise/content',
      'add text "$99" as entPrice style tw:"text-3xl @md:text-5xl font-extrabold text-white"',
      'place entPrice in enterprise/content',
      'add text "/month" as entPer style tw:"text-slate-500 text-sm -mt-3"',
      'place entPer in enterprise/content',
      'add divider as entDiv style tw:"border-slate-800"',
      'place entDiv in enterprise/content',
      'add text "Everything in Pro" as ef1 style tw:"text-slate-400 text-sm"',
      'place ef1 in enterprise/content',
      'add text "SSO & SAML auth" as ef2 style tw:"text-slate-400 text-sm"',
      'place ef2 in enterprise/content',
      'add text "Dedicated account manager" as ef3 style tw:"text-slate-400 text-sm"',
      'place ef3 in enterprise/content',
      'add text "99.99% SLA guarantee" as ef4 style tw:"text-slate-400 text-sm"',
      'place ef4 in enterprise/content',
      'add button "Contact Sales" as entBtn style tw:"mt-auto bg-slate-800 text-white hover:bg-slate-700 px-6 py-3 rounded-xl font-semibold transition-all w-full"',
      'place entBtn in enterprise/content',
    ],
  },
  '3': {
    name: 'Dashboard',
    description: 'Dark sidebar with nav, header with search, stat cards, and activity table',
    commands: [
      // Shell — use stack with flex-col @md:flex-row instead of sidebar for responsive
      'layout stack as shell style tw:"min-h-screen bg-slate-100 flex-col @md:flex-row"',
      // Sidebar
      'layout stack as nav style tw:"bg-slate-900 p-4 @md:p-6 @md:w-72 @md:h-auto @md:shrink-0" gap-lg',
      'place nav in shell/content',
      // Logo
      'layout stack as logoRow axis=x style gap-sm tw:"items-center"',
      'place logoRow in nav/content',
      'add container as logoIcon style tw:"w-8 h-8 bg-gradient-to-br from-violet-500 to-indigo-600 rounded-lg"',
      'place logoIcon in logoRow/content',
      'add text "Nexus" as logo style tw:"text-xl font-bold text-white"',
      'place logo in logoRow/content',
      // Nav menu
      'add menu as navMenu style tw:"flex flex-row @md:flex-col gap-1 mt-2 @md:mt-4 overflow-x-auto @md:overflow-x-visible"',
      'place navMenu in nav/content',
      'add menuItem "Dashboard" as navHome style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium bg-white/10 text-white whitespace-nowrap"',
      'place navHome in navMenu/content',
      'add menuItem "Analytics" as navAnalytics style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-400 hover:text-white hover:bg-white/5 whitespace-nowrap"',
      'place navAnalytics in navMenu/content',
      'add menuItem "Customers" as navCustomers style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-400 hover:text-white hover:bg-white/5 whitespace-nowrap"',
      'place navCustomers in navMenu/content',
      'add menuItem "Products" as navProducts style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-400 hover:text-white hover:bg-white/5 whitespace-nowrap hidden @sm:flex"',
      'place navProducts in navMenu/content',
      'add menuItem "Settings" as navSettings style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-400 hover:text-white hover:bg-white/5 whitespace-nowrap hidden @sm:flex"',
      'place navSettings in navMenu/content',
      // Main content
      'layout stack as main style tw:"p-4 @md:p-8 overflow-y-auto flex-1" gap-lg',
      'place main in shell/content',
      // Header row
      'layout stack as header axis=x justify=between align=center style w-full tw:"flex-wrap gap-2"',
      'place header in main/content',
      'add text "Good morning, Sarah" as greeting style tw:"text-xl @md:text-2xl font-bold text-slate-900"',
      'place greeting in header/content',
      'add input "Search..." as search style tw:"w-full @sm:w-64 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm shadow-sm"',
      'place search in header/content',
      // Stat cards
      'layout grid as stats cols=1 style gap-md tw:"@sm:grid-cols-2 @lg:grid-cols-4"',
      'place stats in main/content',
      'layout stack as stat1 gap=1 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place stat1 in stats/content',
      'add text "Total Revenue" as s1Label style tw:"text-sm font-medium text-slate-500"',
      'place s1Label in stat1/content',
      'add text "$84,254" as s1Val style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900 mt-1"',
      'place s1Val in stat1/content',
      'add text "+12.5% from last month" as s1Change style tw:"text-xs font-medium text-emerald-600 mt-1"',
      'place s1Change in stat1/content',
      'layout stack as stat2 gap=1 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place stat2 in stats/content',
      'add text "Active Users" as s2Label style tw:"text-sm font-medium text-slate-500"',
      'place s2Label in stat2/content',
      'add text "14,829" as s2Val style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900 mt-1"',
      'place s2Val in stat2/content',
      'add text "+8.2% from last month" as s2Change style tw:"text-xs font-medium text-emerald-600 mt-1"',
      'place s2Change in stat2/content',
      'layout stack as stat3 gap=1 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place stat3 in stats/content',
      'add text "Conversion Rate" as s3Label style tw:"text-sm font-medium text-slate-500"',
      'place s3Label in stat3/content',
      'add text "3.24%" as s3Val style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900 mt-1"',
      'place s3Val in stat3/content',
      'add text "-0.4% from last month" as s3Change style tw:"text-xs font-medium text-red-600 mt-1"',
      'place s3Change in stat3/content',
      'layout stack as stat4 gap=1 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place stat4 in stats/content',
      'add text "Avg. Order Value" as s4Label style tw:"text-sm font-medium text-slate-500"',
      'place s4Label in stat4/content',
      'add text "$127.40" as s4Val style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900 mt-1"',
      'place s4Val in stat4/content',
      'add text "+5.1% from last month" as s4Change style tw:"text-xs font-medium text-emerald-600 mt-1"',
      'place s4Change in stat4/content',
      // Recent activity card
      'layout stack as activity gap=0 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place activity in main/content',
      'add text "Recent Activity" as actTitle style tw:"text-lg font-bold text-slate-900 mb-4"',
      'place actTitle in activity/content',
      'add text "New signup: maria@acme.co — 2 min ago" as act1 style tw:"text-sm text-slate-600 py-2 border-b border-slate-100"',
      'place act1 in activity/content',
      'add text "Order #4821 completed — $342.00 — 15 min ago" as act2 style tw:"text-sm text-slate-600 py-2 border-b border-slate-100"',
      'place act2 in activity/content',
      'add text "Support ticket resolved: #1093 — 1 hr ago" as act3 style tw:"text-sm text-slate-600 py-2"',
      'place act3 in activity/content',
    ],
  },
  '4': {
    name: 'Blog Post',
    description: 'Beautifully typeset long-form article with drop cap, pull quote, and tags',
    commands: [
      // Page with soft background
      'layout stack as page align=center style tw:"min-h-screen bg-stone-50 py-8 @md:py-16 px-4"',
      // Article — centered with max-width directly, no center layout wrapper
      'layout stack as article style gap-lg tw:"w-full max-w-3xl"',
      'place article in page/content',
      // Category tag
      'add container as tag style tw:"inline-flex items-center rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700 uppercase tracking-wider w-fit"',
      'place tag in article/content',
      'add text "Engineering" as tagText style tw:"text-xs font-semibold text-indigo-700 uppercase tracking-wider"',
      'place tagText in tag/content',
      // Title
      'add text "The Elegance of Fine-Grained Reactivity" as title style tw:"text-2xl @md:text-4xl font-extrabold text-stone-900 leading-tight tracking-tight block w-full"',
      'place title in article/content',
      // Meta row
      'layout stack as meta axis=x align=center style gap-md tw:"w-full"',
      'place meta in article/content',
      'add container as authorAvatar style tw:"w-10 h-10 rounded-full bg-gradient-to-br from-violet-400 to-indigo-500 shrink-0"',
      'place authorAvatar in meta/content',
      'layout stack as authorInfo gap=0',
      'place authorInfo in meta/content',
      'add text "Sarah Chen" as authorName style tw:"text-sm font-semibold text-stone-900"',
      'place authorName in authorInfo/content',
      'add text "January 28, 2026 \u00b7 12 min read" as dateLine style tw:"text-sm text-stone-500"',
      'place dateLine in authorInfo/content',
      // Hero image placeholder
      'add container as heroImage style tw:"w-full h-48 @md:h-64 rounded-2xl bg-gradient-to-br from-indigo-200 via-purple-200 to-pink-200 shadow-inner"',
      'place heroImage in article/content',
      // Body paragraphs
      'add text "Reactive programming has quietly revolutionized how we build user interfaces. The core idea is simple: instead of manually synchronizing state with the DOM, you declare relationships and let the system handle updates. But not all reactive systems are created equal." as p1 style tw:"text-base @md:text-lg text-stone-700 leading-relaxed block w-full"',
      'place p1 in article/content',
      'add text "The difference between coarse-grained and fine-grained reactivity is the difference between repainting an entire wall versus touching up a single brushstroke. When a signal changes in a fine-grained system, only the exact DOM text node or attribute that depends on it will update. Nothing else is touched." as p2 style tw:"text-base @md:text-lg text-stone-700 leading-relaxed block w-full"',
      'place p2 in article/content',
      // Pull quote
      'add container as pullQuote style tw:"border-l-4 border-indigo-500 pl-4 @md:pl-6 py-4 my-4 w-full"',
      'place pullQuote in article/content',
      'add text "The best abstraction is the one you never have to think about. When reactivity just works, you are free to focus on what matters: building great experiences." as quoteText style tw:"text-lg @md:text-xl text-indigo-900 italic font-medium leading-relaxed"',
      'place quoteText in pullQuote/content',
      // More body
      'add text "Components run once as setup functions. They create signals, bind them to DOM nodes, and the ownership tree ensures everything gets cleaned up automatically when the component is removed. No useEffect, no cleanup arrays, no stale closure bugs." as p3 style tw:"text-base @md:text-lg text-stone-700 leading-relaxed block w-full"',
      'place p3 in article/content',
      'add text "This is not just a performance optimization. It is a fundamentally different mental model that produces simpler, more predictable code. The era of re-render anxiety is over." as p4 style tw:"text-base @md:text-lg text-stone-700 leading-relaxed block w-full"',
      'place p4 in article/content',
      // Divider and footer
      'add divider as sep style tw:"border-stone-200 my-4 w-full"',
      'place sep in article/content',
      // Tags row
      'layout stack as tags axis=x wrap=true style gap-sm tw:"w-full"',
      'place tags in article/content',
      'add container as tag1 style tw:"rounded-full bg-stone-200 px-3 py-1 text-xs font-medium text-stone-600"',
      'place tag1 in tags/content',
      'add text "Reactivity" as tag1Text style tw:"text-xs font-medium text-stone-600"',
      'place tag1Text in tag1/content',
      'add container as tag2 style tw:"rounded-full bg-stone-200 px-3 py-1 text-xs font-medium text-stone-600"',
      'place tag2 in tags/content',
      'add text "Performance" as tag2Text style tw:"text-xs font-medium text-stone-600"',
      'place tag2Text in tag2/content',
      'add container as tag3 style tw:"rounded-full bg-stone-200 px-3 py-1 text-xs font-medium text-stone-600"',
      'place tag3 in tags/content',
      'add text "Frontend" as tag3Text style tw:"text-xs font-medium text-stone-600"',
      'place tag3Text in tag3/content',
    ],
  },
  '5': {
    name: 'Feature Grid',
    description: '3-column feature grid with gradient accent icons and descriptive cards',
    commands: [
      // Page wrapper with subtle gradient
      'layout stack as page align=center style tw:"min-h-screen bg-gradient-to-b from-white to-slate-50 py-10 @md:py-20 px-4 @md:px-8" gap-lg',
      // Badge
      'add container as badge style tw:"inline-flex items-center rounded-full bg-indigo-50 px-4 py-1.5 text-sm font-semibold text-indigo-700 ring-1 ring-indigo-200"',
      'place badge in page/content',
      'add text "Why Choose Environs?" as badgeText style tw:"text-sm font-semibold text-indigo-700"',
      'place badgeText in badge/content',
      // Heading
      'add text "Everything You Need to Build Fast" as heading style tw:"text-2xl @md:text-4xl font-extrabold text-slate-900 text-center tracking-tight max-w-2xl"',
      'place heading in page/content',
      'add text "A modern reactive framework that gets out of your way and lets you ship." as subtitle style tw:"text-base @md:text-lg text-slate-500 text-center max-w-xl"',
      'place subtitle in page/content',
      // Feature grid
      'layout grid as features cols=1 style tw:"gap-4 @sm:gap-6 @md:gap-8 mt-8 max-w-6xl w-full @sm:grid-cols-2 @lg:grid-cols-3"',
      'place features in page/content',
      // Feature 1
      'layout stack as feat1 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat1 in features/content',
      'add container as icon1 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center shadow-lg shadow-blue-500/25"',
      'place icon1 in feat1/content',
      'add text "Fine-Grained Reactivity" as f1Title style tw:"text-lg font-bold text-slate-900"',
      'place f1Title in feat1/content',
      'add text "Only the exact DOM nodes that depend on a signal update when it changes. Zero wasted renders, zero diffing." as f1Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f1Desc in feat1/content',
      // Feature 2
      'layout stack as feat2 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat2 in features/content',
      'add container as icon2 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-violet-500 to-purple-400 flex items-center justify-center shadow-lg shadow-violet-500/25"',
      'place icon2 in feat2/content',
      'add text "No Virtual DOM" as f2Title style tw:"text-lg font-bold text-slate-900"',
      'place f2Title in feat2/content',
      'add text "Direct DOM updates with surgical precision. Your app feels instant because there is nothing between your code and the browser." as f2Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f2Desc in feat2/content',
      // Feature 3
      'layout stack as feat3 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat3 in features/content',
      'add container as icon3 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-400 flex items-center justify-center shadow-lg shadow-emerald-500/25"',
      'place icon3 in feat3/content',
      'add text "Zero Ceremony" as f3Title style tw:"text-lg font-bold text-slate-900"',
      'place f3Title in feat3/content',
      'add text "No hooks, no dependency arrays, no rules of hooks. Components run once. State flows naturally." as f3Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f3Desc in feat3/content',
      // Feature 4
      'layout stack as feat4 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat4 in features/content',
      'add container as icon4 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-amber-500 to-orange-400 flex items-center justify-center shadow-lg shadow-amber-500/25"',
      'place icon4 in feat4/content',
      'add text "Automatic Cleanup" as f4Title style tw:"text-lg font-bold text-slate-900"',
      'place f4Title in feat4/content',
      'add text "Ownership trees handle disposal of effects, timers, and subscriptions. No memory leaks, no manual cleanup." as f4Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f4Desc in feat4/content',
      // Feature 5
      'layout stack as feat5 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat5 in features/content',
      'add container as icon5 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-rose-500 to-pink-400 flex items-center justify-center shadow-lg shadow-rose-500/25"',
      'place icon5 in feat5/content',
      'add text "TypeScript Native" as f5Title style tw:"text-lg font-bold text-slate-900"',
      'place f5Title in feat5/content',
      'add text "Built from the ground up in TypeScript. Full type inference for signals, effects, and component props." as f5Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f5Desc in feat5/content',
      // Feature 6
      'layout stack as feat6 style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-sm hover:shadow-md transition-shadow" gap-md',
      'place feat6 in features/content',
      'add container as icon6 style tw:"w-12 h-12 rounded-xl bg-gradient-to-br from-slate-700 to-slate-500 flex items-center justify-center shadow-lg shadow-slate-500/25"',
      'place icon6 in feat6/content',
      'add text "Tiny Bundle Size" as f6Title style tw:"text-lg font-bold text-slate-900"',
      'place f6Title in feat6/content',
      'add text "Under 5KB gzipped. No bloated runtime, no tree-shaking headaches. Ship less JavaScript to your users." as f6Desc style tw:"text-sm text-slate-500 leading-relaxed"',
      'place f6Desc in feat6/content',
    ],
  },
  '6': {
    name: 'Settings Panel',
    description: 'Clean settings page with sidebar navigation and a well-structured form',
    commands: [
      // Shell — stack that goes col on small, row on md+
      'layout stack as shell style tw:"min-h-screen bg-slate-50 flex-col @md:flex-row"',
      // Left sidebar
      'layout stack as nav style tw:"bg-white border-b @md:border-b-0 @md:border-r border-slate-200 p-4 @md:p-6 @md:w-72 @md:h-auto @md:shrink-0" gap-lg',
      'place nav in shell/content',
      'add text "Settings" as sideTitle style tw:"text-xl font-bold text-slate-900"',
      'place sideTitle in nav/content',
      'add text "Manage your account preferences" as sideSub style tw:"text-sm text-slate-500 -mt-3 hidden @md:block"',
      'place sideSub in nav/content',
      'add menu as sideMenu style tw:"flex flex-row @md:flex-col gap-0.5 mt-2 overflow-x-auto @md:overflow-x-visible"',
      'place sideMenu in nav/content',
      'add menuItem "General" as miGeneral style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium bg-indigo-50 text-indigo-700 whitespace-nowrap"',
      'place miGeneral in sideMenu/content',
      'add menuItem "Security" as miSecurity style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-50 whitespace-nowrap"',
      'place miSecurity in sideMenu/content',
      'add menuItem "Notifications" as miNotif style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-50 whitespace-nowrap"',
      'place miNotif in sideMenu/content',
      'add menuItem "Billing" as miBilling style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-50 whitespace-nowrap"',
      'place miBilling in sideMenu/content',
      'add menuItem "API Keys" as miAPI style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-50 whitespace-nowrap"',
      'place miAPI in sideMenu/content',
      // Spacer then danger zone
      'add divider as navDiv style tw:"border-slate-200 my-4 hidden @md:block"',
      'place navDiv in nav/content',
      'add menuItem "Delete Account" as miDelete style tw:"flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-red-600 hover:bg-red-50 hidden @md:flex"',
      'place miDelete in sideMenu/content',
      // Main form area
      'layout stack as form style tw:"p-4 @md:p-10 max-w-2xl overflow-y-auto flex-1" gap-lg',
      'place form in shell/content',
      'add text "General Settings" as formTitle style tw:"text-xl @md:text-2xl font-bold text-slate-900"',
      'place formTitle in form/content',
      'add text "Update your personal information and preferences." as formSub style tw:"text-sm text-slate-500 -mt-3"',
      'place formSub in form/content',
      // Profile section
      'layout stack as profileCard gap=2 style tw:"rounded-2xl border border-slate-200 bg-white p-4 @md:p-6 shadow-sm"',
      'place profileCard in form/content',
      'add text "Profile" as profileLabel style tw:"text-base font-semibold text-slate-900 mb-4"',
      'place profileLabel in profileCard/content',
      'layout grid as nameRow cols=1 style gap-md tw:"@md:grid-cols-2"',
      'place nameRow in profileCard/content',
      'layout stack as firstNameGroup gap=1',
      'place firstNameGroup in nameRow/content',
      'add text "First Name" as fnLabel style tw:"text-sm font-medium text-slate-700"',
      'place fnLabel in firstNameGroup/content',
      'add input "Jane" as fnInput style tw:"w-full rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"',
      'place fnInput in firstNameGroup/content',
      'layout stack as lastNameGroup gap=1',
      'place lastNameGroup in nameRow/content',
      'add text "Last Name" as lnLabel style tw:"text-sm font-medium text-slate-700"',
      'place lnLabel in lastNameGroup/content',
      'add input "Doe" as lnInput style tw:"w-full rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"',
      'place lnInput in lastNameGroup/content',
      'layout stack as emailGroup gap=1 style tw:"mt-4"',
      'place emailGroup in profileCard/content',
      'add text "Email Address" as emailLabel style tw:"text-sm font-medium text-slate-700"',
      'place emailLabel in emailGroup/content',
      'add input "jane@example.com" as emailInput style tw:"w-full rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"',
      'place emailInput in emailGroup/content',
      'layout stack as bioGroup gap=1 style tw:"mt-4"',
      'place bioGroup in profileCard/content',
      'add text "Bio" as bioLabel style tw:"text-sm font-medium text-slate-700"',
      'place bioLabel in bioGroup/content',
      'add input "Software engineer who loves building reactive UIs." as bioInput style tw:"w-full rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 h-20"',
      'place bioInput in bioGroup/content',
      // Action buttons
      'layout stack as actions axis=x justify=end style gap-sm tw:"mt-2"',
      'place actions in form/content',
      'add button "Cancel" as cancelBtn style tw:"bg-white border border-slate-300 text-slate-700 hover:bg-slate-50 px-5 py-2.5 rounded-lg text-sm font-medium transition-all"',
      'place cancelBtn in actions/content',
      'add button "Save Changes" as saveBtn style tw:"bg-indigo-600 text-white hover:bg-indigo-700 px-5 py-2.5 rounded-lg text-sm font-semibold shadow-sm transition-all"',
      'place saveBtn in actions/content',
    ],
  },
  '7': {
    name: 'E-commerce Product',
    description: 'Product page with image gallery area, details, color picker, size selector, and add-to-cart',
    commands: [
      // Page wrapper
      'layout stack as page style tw:"min-h-screen bg-white py-6 @md:py-12 px-4 @md:px-8"',
      // Product split — use stack that goes col→row for responsive
      'layout stack as product style tw:"max-w-6xl mx-auto flex-col @md:flex-row gap-6 @md:gap-12"',
      'place product in page/content',
      // Left: Image area
      'layout stack as gallery style gap-md tw:"w-full @md:w-1/2 @md:shrink-0"',
      'place gallery in product/content',
      'add container as mainImage style tw:"w-full aspect-square rounded-3xl bg-gradient-to-br from-slate-100 via-slate-50 to-slate-200 flex items-center justify-center shadow-inner"',
      'place mainImage in gallery/content',
      'add text "Product Image" as imgPlaceholder style tw:"text-slate-400 text-lg font-medium"',
      'place imgPlaceholder in mainImage/content',
      // Thumbnail row
      'layout grid as thumbs cols=4 style gap-sm',
      'place thumbs in gallery/content',
      'add container as t1 style tw:"aspect-square rounded-xl bg-slate-100 border-2 border-indigo-500 cursor-pointer"',
      'place t1 in thumbs/content',
      'add container as t2 style tw:"aspect-square rounded-xl bg-slate-100 border-2 border-transparent hover:border-slate-300 cursor-pointer"',
      'place t2 in thumbs/content',
      'add container as t3 style tw:"aspect-square rounded-xl bg-slate-100 border-2 border-transparent hover:border-slate-300 cursor-pointer"',
      'place t3 in thumbs/content',
      'add container as t4 style tw:"aspect-square rounded-xl bg-slate-100 border-2 border-transparent hover:border-slate-300 cursor-pointer"',
      'place t4 in thumbs/content',
      // Right: Details
      'layout stack as details style gap-md tw:"py-0 @md:py-4 flex-1"',
      'place details in product/content',
      // Breadcrumb
      'add text "Home / Audio / Headphones" as breadcrumb style tw:"text-sm text-slate-400"',
      'place breadcrumb in details/content',
      'add text "Premium Wireless Headphones Pro" as prodName style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900 tracking-tight"',
      'place prodName in details/content',
      // Rating row
      'layout stack as rating axis=x align=center style gap-sm',
      'place rating in details/content',
      'add text "4.8 out of 5" as ratingNum style tw:"text-sm font-semibold text-slate-900"',
      'place ratingNum in rating/content',
      'add text "(2,847 reviews)" as reviewCount style tw:"text-sm text-slate-400"',
      'place reviewCount in rating/content',
      // Price
      'layout stack as priceRow axis=x align=center wrap=true style gap-md',
      'place priceRow in details/content',
      'add text "$349.00" as prodPrice style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900"',
      'place prodPrice in priceRow/content',
      'add text "$449.00" as oldPrice style tw:"text-lg text-slate-400 line-through"',
      'place oldPrice in priceRow/content',
      'add container as discountBadge style tw:"rounded-full bg-emerald-100 px-3 py-1"',
      'place discountBadge in priceRow/content',
      'add text "Save 22%" as discountText style tw:"text-xs font-bold text-emerald-700"',
      'place discountText in discountBadge/content',
      'add divider as sep1 style tw:"border-slate-200"',
      'place sep1 in details/content',
      // Color picker
      'add text "Color" as colorLabel style tw:"text-sm font-semibold text-slate-900"',
      'place colorLabel in details/content',
      'layout stack as colors axis=x style gap-sm',
      'place colors in details/content',
      'add container as c1 style tw:"w-8 h-8 rounded-full bg-slate-900 ring-2 ring-offset-2 ring-indigo-500 cursor-pointer"',
      'place c1 in colors/content',
      'add container as c2 style tw:"w-8 h-8 rounded-full bg-stone-300 cursor-pointer hover:ring-2 hover:ring-offset-2 hover:ring-slate-300"',
      'place c2 in colors/content',
      'add container as c3 style tw:"w-8 h-8 rounded-full bg-indigo-600 cursor-pointer hover:ring-2 hover:ring-offset-2 hover:ring-indigo-300"',
      'place c3 in colors/content',
      // Size picker
      'add text "Size" as sizeLabel style tw:"text-sm font-semibold text-slate-900 mt-2"',
      'place sizeLabel in details/content',
      'layout grid as sizes cols=4 style gap-sm',
      'place sizes in details/content',
      'add button "S" as sizeS style tw:"border-2 border-slate-200 bg-white text-slate-700 hover:border-slate-400 py-2.5 rounded-xl text-sm font-medium transition-all"',
      'place sizeS in sizes/content',
      'add button "M" as sizeM style tw:"border-2 border-indigo-600 bg-indigo-50 text-indigo-700 py-2.5 rounded-xl text-sm font-bold"',
      'place sizeM in sizes/content',
      'add button "L" as sizeL style tw:"border-2 border-slate-200 bg-white text-slate-700 hover:border-slate-400 py-2.5 rounded-xl text-sm font-medium transition-all"',
      'place sizeL in sizes/content',
      'add button "XL" as sizeXL style tw:"border-2 border-slate-200 bg-white text-slate-700 hover:border-slate-400 py-2.5 rounded-xl text-sm font-medium transition-all"',
      'place sizeXL in sizes/content',
      'add divider as sep2 style tw:"border-slate-200"',
      'place sep2 in details/content',
      // Add to cart
      'layout stack as cartRow axis=x style gap-md',
      'place cartRow in details/content',
      'add button "Add to Cart" as buyBtn style tw:"flex-1 bg-indigo-600 text-white hover:bg-indigo-700 py-3.5 rounded-xl text-base font-bold shadow-lg shadow-indigo-500/25 transition-all"',
      'place buyBtn in cartRow/content',
      'add button "Save" as wishBtn style tw:"bg-white border-2 border-slate-200 text-slate-600 hover:border-slate-400 hover:text-red-500 px-4 py-3.5 rounded-xl font-medium transition-all"',
      'place wishBtn in cartRow/content',
      // Shipping info
      'add text "Free shipping on orders over $200. 30-day free returns." as shipping style tw:"text-sm text-slate-500 mt-1"',
      'place shipping in details/content',
    ],
  },
  '8': {
    name: 'Team Gallery',
    description: 'Team page with gradient header, profile cards with avatar placeholders, names, and roles',
    commands: [
      // Page
      'layout stack as page style tw:"min-h-screen bg-white"',
      // Gradient header
      'layout stack as header align=center justify=center style tw:"bg-gradient-to-r from-indigo-600 via-violet-600 to-purple-600 py-10 @md:py-20 px-4 @md:px-8" gap-md',
      'place header in page/content',
      'add text "Meet Our Team" as heading style tw:"text-2xl @md:text-4xl font-extrabold text-white tracking-tight text-center"',
      'place heading in header/content',
      'add text "The passionate people building the future of reactive UI" as subtitle style tw:"text-base @md:text-lg text-indigo-200 text-center max-w-lg"',
      'place subtitle in header/content',
      // Team grid
      'layout grid as team cols=1 style tw:"gap-4 @sm:gap-6 @md:gap-8 max-w-6xl mx-auto px-4 @md:px-8 -mt-8 @md:-mt-16 relative z-10 pb-10 @md:pb-20 @sm:grid-cols-2 @lg:grid-cols-4"',
      'place team in page/content',
      // Member 1
      'layout stack as m1 align=center style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-lg hover:shadow-xl transition-shadow text-center" gap-md',
      'place m1 in team/content',
      'add container as a1 style tw:"w-20 @md:w-24 h-20 @md:h-24 rounded-full bg-gradient-to-br from-pink-400 to-rose-500 shadow-lg shadow-pink-500/25"',
      'place a1 in m1/content',
      'add text "Sarah Chen" as n1 style tw:"text-lg font-bold text-slate-900"',
      'place n1 in m1/content',
      'add text "CEO & Co-founder" as r1 style tw:"text-sm text-slate-500 -mt-2"',
      'place r1 in m1/content',
      'add text "Former engineer at Vercel. Passionate about developer experience and beautiful abstractions." as bio1 style tw:"text-sm text-slate-400 leading-relaxed"',
      'place bio1 in m1/content',
      // Member 2
      'layout stack as m2 align=center style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-lg hover:shadow-xl transition-shadow text-center" gap-md',
      'place m2 in team/content',
      'add container as a2 style tw:"w-20 @md:w-24 h-20 @md:h-24 rounded-full bg-gradient-to-br from-blue-400 to-indigo-500 shadow-lg shadow-blue-500/25"',
      'place a2 in m2/content',
      'add text "Alex Rivera" as n2 style tw:"text-lg font-bold text-slate-900"',
      'place n2 in m2/content',
      'add text "CTO & Co-founder" as r2 style tw:"text-sm text-slate-500 -mt-2"',
      'place r2 in m2/content',
      'add text "Reactive systems enthusiast. Previously built real-time infrastructure at Cloudflare." as bio2 style tw:"text-sm text-slate-400 leading-relaxed"',
      'place bio2 in m2/content',
      // Member 3
      'layout stack as m3 align=center style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-lg hover:shadow-xl transition-shadow text-center" gap-md',
      'place m3 in team/content',
      'add container as a3 style tw:"w-20 @md:w-24 h-20 @md:h-24 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 shadow-lg shadow-amber-500/25"',
      'place a3 in m3/content',
      'add text "Priya Patel" as n3 style tw:"text-lg font-bold text-slate-900"',
      'place n3 in m3/content',
      'add text "Head of Design" as r3 style tw:"text-sm text-slate-500 -mt-2"',
      'place r3 in m3/content',
      'add text "Design systems expert. Believes great tools should be as beautiful as they are powerful." as bio3 style tw:"text-sm text-slate-400 leading-relaxed"',
      'place bio3 in m3/content',
      // Member 4
      'layout stack as m4 align=center style tw:"bg-white rounded-2xl border border-slate-200 p-6 @md:p-8 shadow-lg hover:shadow-xl transition-shadow text-center" gap-md',
      'place m4 in team/content',
      'add container as a4 style tw:"w-20 @md:w-24 h-20 @md:h-24 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 shadow-lg shadow-emerald-500/25"',
      'place a4 in m4/content',
      'add text "Marcus Johnson" as n4 style tw:"text-lg font-bold text-slate-900"',
      'place n4 in m4/content',
      'add text "Lead Engineer" as r4 style tw:"text-sm text-slate-500 -mt-2"',
      'place r4 in m4/content',
      'add text "Compiler nerd and runtime optimizer. Makes everything run faster than you thought possible." as bio4 style tw:"text-sm text-slate-400 leading-relaxed"',
      'place bio4 in m4/content',
    ],
  },
  '9': {
    name: 'Navbar + Content',
    description: 'Polished navbar with logo, links, and CTA, plus a hero section with feature highlights',
    commands: [
      // Full page
      'layout stack as page style tw:"min-h-screen bg-white"',
      // Navbar
      'layout stack as navbar axis=x align=center justify=between style tw:"px-4 @md:px-8 py-4 border-b border-slate-100 bg-white/80 backdrop-blur-sm sticky top-0 z-50"',
      'place navbar in page/content',
      // Logo section
      'layout stack as logoSection axis=x align=center style gap-sm',
      'place logoSection in navbar/content',
      'add container as logoMark style tw:"w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600"',
      'place logoMark in logoSection/content',
      'add text "Environs" as brand style tw:"text-xl font-bold text-slate-900"',
      'place brand in logoSection/content',
      // Nav links — hidden on small
      'layout stack as navLinks axis=x style tw:"gap-1 hidden @md:flex"',
      'place navLinks in navbar/content',
      'add button "Features" as link1 style tw:"bg-transparent border-none text-slate-600 hover:text-slate-900 hover:bg-slate-50 px-4 py-2 rounded-lg text-sm font-medium transition-all"',
      'place link1 in navLinks/content',
      'add button "Docs" as link2 style tw:"bg-transparent border-none text-slate-600 hover:text-slate-900 hover:bg-slate-50 px-4 py-2 rounded-lg text-sm font-medium transition-all"',
      'place link2 in navLinks/content',
      'add button "Pricing" as link3 style tw:"bg-transparent border-none text-slate-600 hover:text-slate-900 hover:bg-slate-50 px-4 py-2 rounded-lg text-sm font-medium transition-all"',
      'place link3 in navLinks/content',
      'add button "Blog" as link4 style tw:"bg-transparent border-none text-slate-600 hover:text-slate-900 hover:bg-slate-50 px-4 py-2 rounded-lg text-sm font-medium transition-all"',
      'place link4 in navLinks/content',
      // Right side: sign in + CTA
      'layout stack as navRight axis=x align=center style gap-sm',
      'place navRight in navbar/content',
      'add button "Sign In" as signIn style tw:"bg-transparent border-none text-slate-600 hover:text-slate-900 px-4 py-2 rounded-lg text-sm font-medium transition-all hidden @sm:inline-flex"',
      'place signIn in navRight/content',
      'add button "Get Started" as navCTA style tw:"bg-slate-900 text-white hover:bg-slate-800 px-4 @md:px-5 py-2 @md:py-2.5 rounded-xl text-sm font-semibold shadow-sm transition-all"',
      'place navCTA in navRight/content',
      // Hero section
      'layout stack as hero align=center justify=center style tw:"py-12 @md:py-24 px-4 @md:px-8" gap-lg',
      'place hero in page/content',
      // Announcement banner
      'add container as announcement style tw:"inline-flex items-center gap-2 rounded-full bg-indigo-50 px-4 py-1.5 ring-1 ring-indigo-200"',
      'place announcement in hero/content',
      'add text "New: v2.0 released with streaming SSR support" as annText style tw:"text-sm font-medium text-indigo-700"',
      'place annText in announcement/content',
      // Hero headline
      'add text "The Framework That Respects Your Time" as heroTitle style tw:"text-3xl @md:text-5xl font-extrabold text-slate-900 text-center tracking-tight leading-tight max-w-3xl"',
      'place heroTitle in hero/content',
      'add text "Stop fighting your framework. Environs gives you fine-grained reactivity, automatic cleanup, and a mental model so simple you will forget you are using a framework at all." as heroSub style tw:"text-lg @md:text-xl text-slate-500 text-center max-w-2xl leading-relaxed"',
      'place heroSub in hero/content',
      // CTA row
      'layout stack as heroCtas axis=x wrap=true style gap-md tw:"mt-2 justify-center"',
      'place heroCtas in hero/content',
      'add button "Start Building" as heroPrimary style tw:"bg-indigo-600 text-white hover:bg-indigo-700 px-6 @md:px-8 py-3 @md:py-3.5 rounded-xl text-base font-bold shadow-lg shadow-indigo-500/25 transition-all"',
      'place heroPrimary in heroCtas/content',
      'add button "Read the Docs" as heroSecondary style tw:"bg-white text-slate-700 border border-slate-300 hover:border-slate-400 px-6 @md:px-8 py-3 @md:py-3.5 rounded-xl text-base font-semibold transition-all"',
      'place heroSecondary in heroCtas/content',
      // Feature highlights row
      'layout grid as highlights cols=1 style tw:"gap-6 @md:gap-8 max-w-5xl w-full mt-8 @md:mt-16 border-t border-slate-100 pt-8 @md:pt-16 @md:grid-cols-3"',
      'place highlights in hero/content',
      'layout stack as h1 align=center style gap-sm',
      'place h1 in highlights/content',
      'add text "4.2KB" as h1Stat style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900"',
      'place h1Stat in h1/content',
      'add text "Gzipped runtime. Smaller than most icons." as h1Desc style tw:"text-sm text-slate-500 text-center"',
      'place h1Desc in h1/content',
      'layout stack as h2 align=center style gap-sm',
      'place h2 in highlights/content',
      'add text "60fps" as h2Stat style tw:"text-2xl @md:text-3xl font-extrabold text-slate-900"',
      'place h2Stat in h2/content',
      'add text "Consistent performance. No jank, no dropped frames." as h2Desc style tw:"text-sm text-slate-500 text-center"',
      'place h2Desc in h2/content',
      'layout stack as h3 align=center style gap-sm',
      'place h3 in highlights/content',
      'add text "0ms" as h3Stat style tw:"text-2xl @md:text-3xl font-extrabold text-indigo-600"',
      'place h3Stat in h3/content',
      'add text "Update overhead. Direct DOM writes, no reconciliation." as h3Desc style tw:"text-sm text-slate-500 text-center"',
      'place h3Desc in h3/content',
    ],
  },
  '10': {
    name: 'Kanban Board',
    description: 'Three-column kanban board with colored headers, task cards with priority tags, and assignees',
    commands: [
      // Page shell
      'layout stack as board style tw:"min-h-screen bg-slate-100 p-4 @md:p-8" gap-md',
      // Header bar
      'layout stack as header axis=x justify=between align=center wrap=true style w-full tw:"gap-2"',
      'place header in board/content',
      'layout stack as headerLeft axis=x align=center style gap-md',
      'place headerLeft in header/content',
      'add text "Sprint Board" as boardTitle style tw:"text-xl @md:text-2xl font-bold text-slate-900"',
      'place boardTitle in headerLeft/content',
      'add container as sprintBadge style tw:"rounded-full bg-indigo-100 px-3 py-1"',
      'place sprintBadge in headerLeft/content',
      'add text "Sprint 14" as sprintText style tw:"text-xs font-bold text-indigo-700"',
      'place sprintText in sprintBadge/content',
      'add button "New Task" as newTaskBtn style tw:"bg-indigo-600 text-white hover:bg-indigo-700 px-4 py-2 rounded-lg text-sm font-semibold shadow-sm transition-all"',
      'place newTaskBtn in header/content',
      // Columns
      'layout grid as columns cols=1 style tw:"gap-4 @md:gap-6 mt-2 flex-1 @md:grid-cols-3"',
      'place columns in board/content',
      // --- TO DO column ---
      'layout stack as todo style tw:"bg-white rounded-2xl p-4 shadow-sm border border-slate-200 self-start" gap-sm',
      'place todo in columns/content',
      'layout stack as todoHeader axis=x justify=between align=center style w-full',
      'place todoHeader in todo/content',
      'layout stack as todoTitleRow axis=x align=center style gap-sm',
      'place todoTitleRow in todoHeader/content',
      'add container as todoDot style tw:"w-3 h-3 rounded-full bg-slate-400"',
      'place todoDot in todoTitleRow/content',
      'add text "To Do" as todoTitle style tw:"text-sm font-bold text-slate-700 uppercase tracking-wide"',
      'place todoTitle in todoTitleRow/content',
      'add container as todoCount style tw:"rounded-full bg-slate-100 px-2 py-0.5"',
      'place todoCount in todoHeader/content',
      'add text "4" as todoCountText style tw:"text-xs font-bold text-slate-500"',
      'place todoCountText in todoCount/content',
      // Task cards in To Do
      'layout stack as t1 gap=1 style tw:"rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow cursor-pointer"',
      'place t1 in todo/content',
      'add container as t1Tag style tw:"rounded-full bg-red-100 px-2.5 py-0.5 w-fit"',
      'place t1Tag in t1/content',
      'add text "High Priority" as t1TagText style tw:"text-xs font-semibold text-red-700"',
      'place t1TagText in t1Tag/content',
      'add text "Design system token audit" as t1Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t1Text in t1/content',
      'add text "Review and update all spacing, color, and typography tokens." as t1Desc style tw:"text-xs text-slate-500 mt-1"',
      'place t1Desc in t1/content',
      'layout stack as t2 gap=1 style tw:"rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow cursor-pointer"',
      'place t2 in todo/content',
      'add container as t2Tag style tw:"rounded-full bg-amber-100 px-2.5 py-0.5 w-fit"',
      'place t2Tag in t2/content',
      'add text "Medium" as t2TagText style tw:"text-xs font-semibold text-amber-700"',
      'place t2TagText in t2Tag/content',
      'add text "Write API documentation" as t2Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t2Text in t2/content',
      'layout stack as t3 gap=1 style tw:"rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow cursor-pointer"',
      'place t3 in todo/content',
      'add container as t3Tag style tw:"rounded-full bg-blue-100 px-2.5 py-0.5 w-fit"',
      'place t3Tag in t3/content',
      'add text "Feature" as t3TagText style tw:"text-xs font-semibold text-blue-700"',
      'place t3TagText in t3Tag/content',
      'add text "Set up E2E test suite" as t3Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t3Text in t3/content',
      'layout stack as t4 gap=1 style tw:"rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md transition-shadow cursor-pointer"',
      'place t4 in todo/content',
      'add container as t4Tag style tw:"rounded-full bg-slate-100 px-2.5 py-0.5 w-fit"',
      'place t4Tag in t4/content',
      'add text "Low" as t4TagText style tw:"text-xs font-semibold text-slate-500"',
      'place t4TagText in t4Tag/content',
      'add text "Optimize bundle size" as t4Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t4Text in t4/content',
      // --- IN PROGRESS column ---
      'layout stack as inProgress style tw:"bg-white rounded-2xl p-4 shadow-sm border border-slate-200 self-start" gap-sm',
      'place inProgress in columns/content',
      'layout stack as ipHeader axis=x justify=between align=center style w-full',
      'place ipHeader in inProgress/content',
      'layout stack as ipTitleRow axis=x align=center style gap-sm',
      'place ipTitleRow in ipHeader/content',
      'add container as ipDot style tw:"w-3 h-3 rounded-full bg-blue-500"',
      'place ipDot in ipTitleRow/content',
      'add text "In Progress" as ipTitle style tw:"text-sm font-bold text-slate-700 uppercase tracking-wide"',
      'place ipTitle in ipTitleRow/content',
      'add container as ipCount style tw:"rounded-full bg-blue-50 px-2 py-0.5"',
      'place ipCount in ipHeader/content',
      'add text "2" as ipCountText style tw:"text-xs font-bold text-blue-600"',
      'place ipCountText in ipCount/content',
      // Task cards in In Progress
      'layout stack as t5 gap=1 style tw:"rounded-xl border-2 border-blue-200 bg-blue-50/50 p-4 shadow-sm"',
      'place t5 in inProgress/content',
      'add container as t5Tag style tw:"rounded-full bg-red-100 px-2.5 py-0.5 w-fit"',
      'place t5Tag in t5/content',
      'add text "High Priority" as t5TagText style tw:"text-xs font-semibold text-red-700"',
      'place t5TagText in t5Tag/content',
      'add text "Implement auth flow" as t5Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t5Text in t5/content',
      'add text "OAuth2 + magic link support for login/signup." as t5Desc style tw:"text-xs text-slate-500 mt-1"',
      'place t5Desc in t5/content',
      'layout stack as t5Footer axis=x justify=between align=center style tw:"mt-2"',
      'place t5Footer in t5/content',
      'add container as t5Avatar style tw:"w-6 h-6 rounded-full bg-gradient-to-br from-violet-400 to-indigo-500"',
      'place t5Avatar in t5Footer/content',
      'add text "2d left" as t5Due style tw:"text-xs text-slate-400"',
      'place t5Due in t5Footer/content',
      'layout stack as t6 gap=1 style tw:"rounded-xl border-2 border-blue-200 bg-blue-50/50 p-4 shadow-sm"',
      'place t6 in inProgress/content',
      'add container as t6Tag style tw:"rounded-full bg-amber-100 px-2.5 py-0.5 w-fit"',
      'place t6Tag in t6/content',
      'add text "Medium" as t6TagText style tw:"text-xs font-semibold text-amber-700"',
      'place t6TagText in t6Tag/content',
      'add text "Build notification system" as t6Text style tw:"text-sm font-medium text-slate-900 mt-1"',
      'place t6Text in t6/content',
      'layout stack as t6Footer axis=x justify=between align=center style tw:"mt-2"',
      'place t6Footer in t6/content',
      'add container as t6Avatar style tw:"w-6 h-6 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500"',
      'place t6Avatar in t6Footer/content',
      'add text "5d left" as t6Due style tw:"text-xs text-slate-400"',
      'place t6Due in t6Footer/content',
      // --- DONE column ---
      'layout stack as done style tw:"bg-white rounded-2xl p-4 shadow-sm border border-slate-200 self-start" gap-sm',
      'place done in columns/content',
      'layout stack as doneHeader axis=x justify=between align=center style w-full',
      'place doneHeader in done/content',
      'layout stack as doneTitleRow axis=x align=center style gap-sm',
      'place doneTitleRow in doneHeader/content',
      'add container as doneDot style tw:"w-3 h-3 rounded-full bg-emerald-500"',
      'place doneDot in doneTitleRow/content',
      'add text "Done" as doneTitle style tw:"text-sm font-bold text-slate-700 uppercase tracking-wide"',
      'place doneTitle in doneTitleRow/content',
      'add container as doneCount style tw:"rounded-full bg-emerald-50 px-2 py-0.5"',
      'place doneCount in doneHeader/content',
      'add text "3" as doneCountText style tw:"text-xs font-bold text-emerald-600"',
      'place doneCountText in doneCount/content',
      // Task cards in Done
      'layout stack as t7 gap=1 style tw:"rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"',
      'place t7 in done/content',
      'add text "Project setup and scaffolding" as t7Text style tw:"text-sm font-medium text-slate-500 line-through"',
      'place t7Text in t7/content',
      'layout stack as t8 gap=1 style tw:"rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"',
      'place t8 in done/content',
      'add text "CI/CD pipeline configuration" as t8Text style tw:"text-sm font-medium text-slate-500 line-through"',
      'place t8Text in t8/content',
      'layout stack as t9 gap=1 style tw:"rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"',
      'place t9 in done/content',
      'add text "Database schema design" as t9Text style tw:"text-sm font-medium text-slate-500 line-through"',
      'place t9Text in t9/content',
    ],
  },
};

// ---------------------------------------------------------------------------
// Lookup helper
// ---------------------------------------------------------------------------

export function getDemoCommands(id: string): string[] | null {
  const demo = DEMOS[id];
  return demo ? demo.commands : null;
}
